### PR TITLE
htslib 1.13 compatibility

### PR DESCRIPTION
**Pull request by charlesgregory**
Also added documentation on how I found the differences between htslib 1.12 and htslib 1.13.

### CODE REVIEW

**Comment by jblachly** [comment]
@charlesgregory LGTM. Did you pull updates to existing headers in an automated way (e.g. dstep workflow) or simply eyeball the header diff  and copy-paste?

**Comment by charlesgregory** [comment]
Eyeball copy-paste from diff. Process is described in the markdown file I added.

On Jul 28, 2021, at 10:42 PM, James S Blachly, MD ***@***.***> wrote:

﻿

@charlesgregory<https://github.com/charlesgregory> LGTM. Did you pull updates to existing headers in an automated way (e.g. dstep workflow) or simply eyeball the header diff and copy-paste?

**Comment by jblachly** [comment]
Will this break the patches in `dstep/patches` ?

**Comment by charlesgregory** [comment]
Probably, I wasn't sure how those worked so they are probably already broke from the htslib 1.12 compatibility changes. Honestly we need an automated system (probably what you were going for with the dstep folder) for this but the bindings always have to have some manual changes (inline functions for instance).

On Jul 28, 2021, at 11:04 PM, James S Blachly, MD ***@***.***> wrote:

﻿

Will this break the patches in dstep/patches ?

**Comment by charlesgregory** [comment]
Are we good to merge this in? If I am correct dhtslib is still compatible with 1.113 without these changes (minus the new functions).

**Comment by jblachly** [comment]
We can merge it if you pinky-swear to come up with an automated solution/fix the patches in the `dstep` folder. This will save us major grief when it comes to updating in the future so we don't accidentally miss any hand-tunes/inlines/rewrites we have added on that could be copied over if there's a large change in the source.

**Comment by jblachly** [comment]
> for this but the bindings always have to have some manual changes (inline functions for instance).

@charlesgregory  the patches in `dstep/` are meant precisely to capture the difference between the automated conversion and our manual changes, so that we don't lose the manual changes in the future, and could potentially be applied on top of future automated changes

**Pull request merged**
