### PR TITLE
Bgzf reader

### LINKED ISSUE #25: BGZFile range implementation does not conform to Phobos range rules
For the ```empty``` function we are mutating or progressing the range with ```bgzf_getline```.
https://github.com/blachlylab/dhtslib/blob/5f47b4511ef13c51d8bb0004012de7235e6b6c67/source/dhtslib/bgzf.d#L75-L86
For the ```popFront``` function we are not progressing the range, only freeing the line string and not retrieving a new one.
https://github.com/blachlylab/dhtslib/blob/5f47b4511ef13c51d8bb0004012de7235e6b6c67/source/dhtslib/bgzf.d#L88-L98

This implementation works well enough for a foreach. However, when trying to wrap a ```BGZFile``` range for use as say a fastq file reader, it doesn't perform correctly.

From the dlang [website](https://dlang.org/phobos/std_range_primitives.html#isInputRange):
> The following are rules of input ranges are assumed to hold true in all Phobos code. These rules are not checkable at compile-time, so not conforming to these rules when writing ranges or range based code will result in undefined behavior.
> * r.empty returns false if and only if there is more data available in the range.
> * **_r.empty evaluated multiple times, without calling r.popFront, or otherwise mutating the range object or the underlying data, yields the same result for every evaluation._**
> * r.front returns the current element in the range. It may return by value or by reference.
> * r.front can be legally evaluated if and only if evaluating r.empty has, or would have, equaled false.
> * r.front evaluated multiple times, without calling r.popFront, or otherwise mutating the range object or the underlying data, yields the same result for every evaluation.
> * **_r.popFront advances to the next element in the range._**
> * r.popFront can be called if and only if evaluating r.empty has, or would have, equaled false.

### PR DESCRIPTION
**Pull request by charlesgregory**
This fixes #25. Also adds fastq reader.

### CODE REVIEW

**Comment by jblachly** [comment]
This now no longer matches the range behavior of the other readers; why is this one special or different?

**Comment by charlesgregory** [comment]
Are there other readers that do not conform to the range rules? We should update them as well. Can you provide an example? This is important as if we want to wrap them within another range they need to behave correctly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jblachly** [comment]
What happens if you try to iterate the BGZF twice ( `foreach(rec; bgzfile) ... (foreach(recagain:bgzfile)` ) ?

**Comment by charlesgregory** [comment]
We will attempt to fix copy with postblit constructor.

**Pull request merged**
